# Basic
title: Yao Xiao
subtitle: Engineer
description: Coding & Game 
# Title inside avatar
avatarTitle: xyshow
# Description inside avatar
avatarDesc: ML, Kubeflow, Kubernetes
url: "https://raw.githubusercontent.com/PatrickXYS/PatrickXYS.githuo.io/master/images/avatar.jpg"

# Determine if github page generate TOC automatically
enableToc: true

# Social
social:
    github: PatrickXYS
    mail: chuckxiao1@gmail.com


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Homepage of Blog

# Navigation buttons in the front page.s
nav:
    - {title: Blogs, description: archive, url: '/archive'}   
    - {title: Title, description: tags, url: '/tags'}      
    - {title: Technical Support, description: support, url: '/support'}      
    - {title: About me, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


